config/routes.rb
Rails.application.routes.draw do


  get '/home' => 'pages#home', :as => 'home'

resources :users, :sports, :scoreboards, :messages, :leagues

  get  '/login' => 'session#new', :as => 'login'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy', :as => 'logout'
  get '/invite/:league_id/:sport_id' => 'users#invite'
  post '/invite/:league_id/:sport_id' => 'users#do_invite'
  get '/leagues/new/:sport_id' => 'leagues#new'
  get '/leagues/:league_id/messages' => 'messages#index', :as => 'league_messages'
  post '/leagues/:league_id/messages' => 'messages#create', :as => 'create_messages'
  get '/leagues/:league_id/scoreboard' => 'scoreboards#show', :as => 'league_scoreboard'
  post '/leagues/:league_id/scoreboard' => 'scoreboards#update'
  delete '/leagues/:id' => 'leagues#destroy'
  # get '/leagues/index' => 'leagues#index'

end

app/models/league.rb
class League < ActiveRecord::Base
  has_one :scoreboard
  has_and_belongs_to_many :users
  belongs_to :user, foreign_key: "creator_id"
  has_many :messages
  belongs_to :sport
  has_one :sport
end

app/models/leagues_users.rb
class LeaguesUsers < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :league
end

app/models/scoreboard.rb
class Scoreboard < ActiveRecord::Base
  belongs_to :league
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :leagues
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  email           :text
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :leagues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by( :id => session[:user_id])
    session[:user_id] = nil unless @current_user
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def new
    @league = League.new
    @sport = Sport.find params[:sport_id]
  end

  def create
    league = League.create!({name: params[:league][:name], creator_id: @current_user.id, image: params[:league][:image], sport_id: params[:league][:sport_id]})
    redirect_to "/invite/#{league.id}/#{params[:league][:sport_id]}"
  end

  def show
    @league = League.find params[:id]
    @sport = Sport.find @league.sport_id

  end


    def edit
      @league = League.find params[:id]
    end

    def update
      league = League.find params[:id]
      league.update( image: params[:league][:image], name: params[:league][:name] )
     redirect_to league_path
    end

    def destroy

      league = League.find params[:id]
      league.destroy

      redirect_to leagues_path

    end

  def index
    @leagues = League.where(creator_id: @current_user.id)
  end

  # private
  #   def user_params
  #     params.require(:league).permit(image: params[:league][:image], name: params[:league][:name])
  #   end



end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

def index
  @league = League.find params[:league_id]
  # binding.pry
  @messages = @league.messages
  @message = Message.new
end

def create
  # binding.pry
message = Message.create! message_params

# ({name: params[:event][:name], user_id: @current_user.id})
flash[:notice] = "Post successfully created"
redirect_to league_messages_path(params[:league_id])
end

def show

end

def new
end

private
  def message_params
    params.require(:message).permit(:message, :league_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/scoreboards_controller.rb
class ScoreboardsController < ApplicationController
  # def index
  #   # @league = League.find params[:league_id]
  #   # @users = User.
  #   # @league = League.find params[:league_id]
  #   # # binding.pry
  #   # @scoreboard = @league.scoreboards
  #   # @league = League.find params[:league_id]
  #   # binding.pry
  #   # @scoreboard = @league.scoreboard
  #
  #   # scores
  #   # elo
  #   # save these in instance variables @scores @users @leagues
  # end

  def show
    @league = League.find params[:league_id]
    @creator = User.find @league.creator_id
    league_users = LeaguesUsers.where :league_id => @league.id
    @user_scores = []
    league_users.each do |league_user|
      user_score = {}
      user_score[:user_name] = (User.find league_user.user_id).name
      user_score[:score] = league_user.score
      @user_scores << user_score
    end

    # binding.pry
  end

  def update
    @league = League.find params[:league_id]
    entry = LeaguesUsers.find_by :league_id => @league.id, :user_id => @current_user.id
    # binding.pry
    entry.score = params[:wins].to_i + (entry.score || 0)

    entry.save

    redirect_to league_scoreboard_path(@league.id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :authenticate, :only =>[:new]

  def new
    # Show the login form
  end


  def create
    # Process the login form when it is submitted
    user = User.find_by :email => params[:email]

    if user.present? && user.authenticate( params[:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in"
      redirect_to leagues_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
  end
end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully logged out"
    redirect_to login_path

  end

  private
  def authenticate
    # redirect_to :back if @current_user
    redirect_to leagues_path if @current_user
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.all
  end

  def new
    # Show the login form
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to users_path
    else
      render :new
  end
end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params if user.authenticate( params[:user][:password] )

    redirect_to user
  end

  def destroy
    user = User.find params[:id]
    user.destroy

    redirect_to users_path
  end

  def invite
    @users = User.all
    @sport = Sport.find(params[:sport_id])
  end

  def do_invite
    users = User.find params[:users]
    sport = Sport.find params[:sport_id]
    league = League.find params[:league_id]
    league.users = users
    league.users << @current_user
    league.save
    # binding.pry

    # binding.pry
    #do something useful
    redirect_to leagues_path
  end




private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% @events.each do  |e|%>
  <%= e.message %>
<% end %>

<%= form_for @event do |e| %>
<%= e.hidden_field :league_id, :value => @league.id%>
<%= e.label :message %> <br />
<%= e.text_area :message, :size => "40x3" %>
<%= submit_tag("Post") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Hind:400,600|Asap|Cantarell|Droid+Sans+Mono|Sintony:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,100|Poppins:400,600|Varela' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700|Varela' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,900,900italic,100|Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

<!--"Show all users"  (/users) ALL THE TIME
" View a profile"  (/users/12) IF I AM LOGGED IN
" Edit a user" (/users/12/edit) IF I AM LOGGED IN
" Delete an Account" (/users/12/delete) _ IF I AM LOGGED IN
" Logout" (/user/logout) - IF I AM LOGGED IN
" Create an account" (/users/new )- IF I AM NOT LOGGED IN
-->
<header>

  <div class="box hidden">
    <img src="/assets/logo2.png" alt="logotwo" class="logo2">
    <br><ul>
    <% if @current_user %>
    <li>  <%= link_to "Create new league", sports_path %></li>
      <li>   <%= link_to  "Existing leagues", leagues_path %></li>
      <li>   <%= link_to "All users", users_path %></li>
      <li>   <%= link_to "View Profile", @current_user %></li>
      <li>   <%= link_to "Edit profile", edit_user_path(@current_user) %></li>
  <% end %></ul>
  </div>


<nav>
<% if @current_user %>
  <%= link_to "Logout", logout_path, :method => :delete%>
  <%#= link_to "Create new league", sports_path %>
    <%#= link_to  "Existing leagues", leagues_path %>
     <!-- location -->
    <%#= link_to "All users", users_path %>
    <%#= link_to "View Profile", @current_user %>
    <%#= link_to "Edit profile", edit_user_path(@current_user) %>
    <!-- <%= link_to "Delete Account", user_path(@current_user), :method => :delete %> -->

    <img src="/assets/logo.png" alt="logo" class="logo">
  <%#= link_to "Premiere", home_path %>
<% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Log in", login_path	 %>
    <!-- <%= link_to "Login", login_path %> -->
  <% end %>
</nav>
</header>











  <!-- <% if @current_user %>
  <p>Your email is <%#= @current_user.email %></p>
  <% end %> -->


  <% if flash[:error] %>
  <p><%=flash[:error] %></p>
  <% end %>

<div class="container">
<%= yield %></div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/sports/index.html.erb
<h4>This should show all of the sports</h4>

<ul>
  <% @sports.each do |sport| %>
    <li>
      <a href="/sports/<%= sport.name %>">
        <%= sport.name %>
      </a>


    </li>
  <% end  %>
</ul>

app/views/leagues/edit.html.erb
<div class="row">
  <div class="col-md-4">
      </div>
    <div class="col-md-4">



<div class="signup">
  <h5>Edit League</h5>

<%= form_for @league do |f| %>



<p>
  <%#= f.label :name %>
  <%= f.text_field :name, class: "color", :required => true %>
</p>

<p>
  <%#= f.label :image %>
    <%= f.text_field :image, class: "color", :required => true %>
</p>

<%= f.submit "Update", :class => "updateButton" %>
<% end %>
</div>
</div>
</div>

app/views/leagues/index.html.erb
<h6>This should show all of the users leagues</h6>




<ul class="grid">
  <% @leagues.each do |league| %>
    <li>
      <a href="/leagues/<%= league.id %>">
        <%= league.name %>
        <%= image_tag league.image, :class => 'feature' %>

      </a>


    </li>
  <% end  %>
</ul>

app/views/leagues/new.html.erb
<div class="row">
  <div class="col-md-4">
      </div>
    <div class="col-md-4">




<div class="signup">
  <h5> New League</h5>

<%= form_for @league do | f | %>
<p>
  <%= f.hidden_field "sport_id", value: @sport.id%>
  <%#= f.label :name %>
  <%= f.text_field :name, class: "color2", value: "name", :required => true %>
</p>

<p>
  <%#= f.label :image %>
    <%= f.text_field :image, class: "color2", value: "image", :required => true %>
</p>


<%= f.submit class: "updateButton" %>
<% end %>
</div>
</div>
</div>

app/views/leagues/show.html.erb
<div class="row">
  <div class="col-md-12">


<h2><%= @league.name %></h2><br>

<h5><%= @sport.name %></h5>

<div class="row">
  <div class="col-md-4">

<%= image_tag @league.image, :class => 'pic' %>

</div>

<div class="col-md-4  form" >
  <div class="league">


  <!-- <p><img src=<%#= @league.image  %> :class => 'feature'></p> -->
  <%= link_to "Events", league_messages_path(@league.id), class: "color" %><br><br><br>
  <%= link_to "Scoreboard", league_scoreboard_path(@league.id), class: "color"%></div><br>

      <div class="bottom">

    <%= link_to "Delete", league_path(@league.id), :class => "deleteButton", :method => :delete, :data => { :confirm => "Delete?" } %>

    <%= link_to "Update", edit_league_path(@league.id), :class => "updateButton" %><div>

</div>
</div>
</div>

app/views/messages/index.html.erb
<h2><%= link_to @league.name, league_path(@league.id)%></h2><br>


<% @messages.each do  |m|%>
  <%= m.message %>
<% end %>

<%= form_for @message, :url => {:action => :create} do |m| %>
<%= m.hidden_field :league_id, :value => @league.id %>
<h5><%= m.label :events %> </h5><br/>
<%= m.text_area :message, :size => "40x3", :class => "events" %>
<%= submit_tag "Post", :class => "updateButton" %>
<% end %>

app/views/pages/home.html.erb
<!-- <img src="assets/home.jpg" alt="home">
<body background="assets/home"></body> -->

<!-- body {
    background-image: url("img_tree.png");
    background-repeat: no-repeat;
    background-position: right top;
    background-attachment: fixed;
} -->

<!-- <div style="background-image:url('assets/home.jpg');width:100vw;height:900px;background-repeat:no-repeat;opacity:.8;"> -->

<!-- </div> -->

<div class="skate">
  <h1>Play.</h1>


</div>

app/views/scoreboards/index.html.erb
<h2>This should show the scoreboard with players and points</h2>

app/views/scoreboards/show.html.erb
<h2><%= link_to @league.name, league_path(@league.id)%></h2>
<ul>
  <!-- <li><%#= @creator.name %></li> -->
  <% @user_scores.each do |user_score| %>
    <li><%= user_score[:user_name] %> <%= user_score[:score] %></li>
  <% end %>
</ul>

<%= form_tag do %>
  <p>
    <%#= label_tag "Your wins", :class => "font" %>
    <%= number_field_tag :wins, type="Your wins", :class => "color"  %>
    <%= submit_tag "Update", :class => "updateButton" %>
  </p>
<% end %>

app/views/session/new.html.erb
<div class="row">
  <div class="col-md-4">
      </div>
    <div class="col-md-4">

<div class="signup">

  <h3>Login</h3>

<% if flash[:success] %>
  <p><%=flash[:success] %></p>
<% end %>

<% if flash[:error] %>
  <p><%=flash[:error] %></p>
<% end %>

<%= form_tag login_path do %>


<p>
  <%#= label_tag :email %>
  <%= email_field_tag :email, type="email", :class => "color" %>
</p>

<p>
  <%#= label_tag :password %>
  <%= password_field_tag :password, type="password", :class => "color" %>
</p>



<%= submit_tag "Login", :class => "updateButton" %>

<% end %>
</div>
</div>

  <!-- <div class="col-md-3">
  </div>

</div>
</div> -->

app/views/sports/index.html.erb
<div class="sport">

<h4>Select a <br>sport.</h4>

<ul>
  <% @sports.each do |sport| %>
    <li>
      <a href="/leagues/new/<%= sport.id%>">
        <%= sport.name %>
      </a>


    </li>
  <% end  %>
</ul>


</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  <% end %>



<%= form_for @user do |f| %>



<p>
  <%= f.label :name, class: "font" %>
  <%= f.text_field :name, class: "color2", :required => true %>
</p>

<p>
  <%= f.label :image, class: "font" %>
    <%= f.text_field :image, class: "color2", :required => true %>
</p>

<p>
  <%= f.label :email, class: "font" %>
  <%= f.email_field :email, class: "color2", :required => true %>
</p>

<p>
  <%= f.label :password, class: "font" %>
  <%= f.password_field :password, class: "color2", :required => true %>
</p>

<p>
  <%= f.label :password_confirmation, class: "font" %>
  <%= f.password_field :password_confirmation, class: "color2", :required => true %>
</p>

<%= f.submit "Update", :class => "updateButton" %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-4">
      </div>
    <div class="col-md-4">

<div class="edit">
    <h5>Edit profile</h5>

<%= render :partial => 'form' %>
</div>
  <!-- <div class="col-md-4">
  </div> -->
</div>

app/views/users/index.html.erb
<% @users.each do |u| %>
  <ul>
    <li>Username: <%= link_to(u.name, user_path(u) ) %></li>
    <li>Email: <%= u.email %></li>
    <li>Password digest: <%= u.password_digest %></li>
  </ul>
<% end %>

app/views/users/invite.html.erb
<div class="row">
  <div class="col-md-4">
      </div>
    <div class="col-md-4">



<h5>Invite a user for <%= @sport.name%></h5>
<!-- <%#= form_tag  %> -->

<%= form_tag(method: "POST") do %>
  <%#= label_tag(:q, "Search for:") %>
  <%= select_tag "users", options_from_collection_for_select(@users, "id", "email"), :multiple => true%>
  <!-- <%#= text_field_tag(:user_id) %> -->
  <%= submit_tag("Invite Friend") %>
<% end %>
<%#= @users %>

</div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4">
      </div>
    <div class="col-md-4">




<div class="signup">
  <h3>Sign up</h3>
<%= render :partial => 'form' %></div>


</div>
</div>

app/views/users/show.html.erb
<!-- <h1>Profile</h1> -->
<div class="row">
  <div class="col-md-12">
<h2><%= @user.name %></h2>
</div>
</div>

<div class="row">
  <div class="col-md-4">

<% if @user.image %>
<%= image_tag @user.image, :class => 'profile' %>
<% end %>
</div>

<div class="col-md-4  form" >

<div class="user">
<%= form_for @user do |f| %>
  <p>
    <% f.label :name %>
    <%= f.text_field :name, class: "color", :required => true %>
  </p>

  <p>
    <% f.label :email %>
    <%= f.email_field :email, class: "color", :required => true %>
  </p></div>
<%= f.submit "Update", :class => "updateButton" %>
<% end %>
<%#= link_to( "Edit user", edit_user_path(@user) ) %>
<%= link_to "Delete", user_path(@user), :class => "deleteButton", :method => :delete %></div>

</div>
</div>